-- MySQL Script generated by MySQL Workbench
-- Fri May  5 20:47:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WatchDog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WatchDog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WatchDog` DEFAULT CHARACTER SET utf8 ;
USE `WatchDog` ;

-- -----------------------------------------------------
-- Table `WatchDog`.`Websites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WatchDog`.`Websites` (
  `hostname` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`hostname`),
  UNIQUE INDEX `hostname_UNIQUE` (`hostname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WatchDog`.`IPs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WatchDog`.`IPs` (
  `ip` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ip`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WatchDog`.`Responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WatchDog`.`Responses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` SMALLINT NOT NULL,
  `time` DATETIME NOT NULL,
  `IP_ip` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Responses_IP1_idx` (`IP_ip` ASC),
  CONSTRAINT `fk_Responses_IP1`
    FOREIGN KEY (`IP_ip`)
    REFERENCES `WatchDog`.`IPs` (`ip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WatchDog`.`Websites_has_IPs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WatchDog`.`Websites_has_IPs` (
  `Websites_hostname` VARCHAR(255) NOT NULL,
  `IPs_ip` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Websites_hostname`, `IPs_ip`),
  INDEX `fk_Websites_has_IPs_IPs1_idx` (`IPs_ip` ASC),
  INDEX `fk_Websites_has_IPs_Websites1_idx` (`Websites_hostname` ASC),
  CONSTRAINT `fk_Websites_has_IPs_Websites1`
    FOREIGN KEY (`Websites_hostname`)
    REFERENCES `WatchDog`.`Websites` (`hostname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Websites_has_IPs_IPs1`
    FOREIGN KEY (`IPs_ip`)
    REFERENCES `WatchDog`.`IPs` (`ip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
